"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { Plane, BarChart3, Zap, Shield, ArrowRight, ChevronRight } from "lucide-react";

const stats = [
    { label: "Applications Tracked", value: "2.4M+" },
    { label: "AI Documents Generated", value: "890K+" },
    { label: "Avg. Match Accuracy", value: "94%" },
    { label: "Time Saved / Week", value: "12hrs" },
];

const features = [
    {
        icon: Zap,
        title: "Intelligent Auto-Match",
        description:
            "Our semantic AI engine vectors your profile against every scraped listing, alerting you only when the match score exceeds 85%.",
    },
    {
        icon: BarChart3,
        title: "Executive Pipeline",
        description:
            "A precision Kanban board inspired by air traffic control. Track every application from runway to offer with zero friction.",
    },
    {
        icon: Shield,
        title: "ATS-Bypass Documents",
        description:
            "Cover letters and CVs generated by an elite-headhunter AI. Calibrated to pass Applicant Tracking Systems and impress hiring managers.",
    },
];

export default function LandingPage() {
    return (
        <main className="min-h-screen bg-[#FAF9F6] dark:bg-charcoal text-charcoal dark:text-white hud-grid transition-colors duration-300">
            {/* Navigation */}
            <nav className="fixed top-0 left-0 right-0 z-50 glass border-b border-black/5 dark:border-white/5">
                <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-8 h-8 bg-gold rounded-sm flex items-center justify-center">
                            <Plane className="w-4 h-4 text-charcoal rotate-45" />
                        </div>
                        <span className="font-display text-xl font-semibold tracking-tight">
                            Aero<span className="text-gold">Hire</span>
                        </span>
                    </div>
                    <div className="hidden md:flex items-center gap-8">
                        <Link href="#features" className="text-steel-dark dark:text-steel hover:text-charcoal dark:hover:text-white transition-colors text-sm">
                            Features
                        </Link>
                        <Link href="#pricing" className="text-steel-dark dark:text-steel hover:text-charcoal dark:hover:text-white transition-colors text-sm">
                            Pricing
                        </Link>
                        <Link href="/login" className="btn-secondary py-2 text-sm">
                            Sign In
                        </Link>
                        <Link href="/register" className="btn-primary py-2 text-sm">
                            Start Free
                        </Link>
                    </div>
                </div>
            </nav>

            {/* Hero Section */}
            <section className="relative min-h-screen flex items-center pt-20">
                {/* Decorative lines */}
                <div className="absolute inset-0 overflow-hidden pointer-events-none">
                    <div className="absolute top-1/2 left-0 w-full h-px bg-gradient-to-r from-transparent via-gold/10 to-transparent" />
                    <div className="absolute top-1/3 left-0 w-full h-px bg-gradient-to-r from-transparent via-black/5 dark:via-white/5 to-transparent" />
                    {/* Floating orbs */}
                    <motion.div
                        className="absolute top-32 right-20 w-64 h-64 rounded-full"
                        style={{
                            background: "radial-gradient(circle, rgba(212,175,55,0.08) 0%, transparent 70%)",
                        }}
                        animate={{ scale: [1, 1.1, 1], opacity: [0.5, 0.8, 0.5] }}
                        transition={{ duration: 6, repeat: Infinity, ease: "easeInOut" }}
                    />
                    <motion.div
                        className="absolute bottom-40 left-20 w-48 h-48 rounded-full"
                        style={{
                            background: "radial-gradient(circle, rgba(27,38,59,0.6) 0%, transparent 70%)",
                        }}
                        animate={{ scale: [1, 1.15, 1] }}
                        transition={{ duration: 8, repeat: Infinity, ease: "easeInOut", delay: 2 }}
                    />
                </div>

                <div className="max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-2 gap-16 items-center">
                    {/* Left: Copy */}
                    <div>
                        <motion.div
                            initial={{ opacity: 0, y: 30 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
                        >
                            <div className="inline-flex items-center gap-2 px-3 py-1.5 glass-gold rounded-full mb-8">
                                <div className="w-1.5 h-1.5 rounded-full bg-gold animate-pulse" />
                                <span className="text-gold text-xs font-medium font-sans tracking-widest uppercase">
                                    Now in Beta · Executive Access
                                </span>
                            </div>

                            <h1 className="font-display text-6xl lg:text-7xl font-semibold leading-tight mb-6">
                                Your Career,
                                <br />
                                <span className="text-gold-gradient">Engineered</span>
                                <br />
                                for Altitude.
                            </h1>

                            <p className="text-steel text-lg leading-relaxed mb-10 max-w-md font-sans">
                                AeroHire is the AI-powered operations centre for serious professionals.
                                Auto-match against thousands of roles, generate precision documents,
                                and track every step of your ascent.
                            </p>

                            <div className="flex flex-wrap gap-4">
                                <Link href="/register">
                                    <motion.button
                                        className="btn-primary text-base px-8 py-4"
                                        whileHover={{ scale: 1.02 }}
                                        whileTap={{ scale: 0.98 }}
                                    >
                                        Begin your ascent
                                        <ArrowRight className="w-4 h-4" />
                                    </motion.button>
                                </Link>
                                <Link href="/pipeline">
                                    <motion.button
                                        className="btn-secondary text-base px-8 py-4"
                                        whileHover={{ scale: 1.02 }}
                                        whileTap={{ scale: 0.98 }}
                                    >
                                        View pipeline demo
                                        <ChevronRight className="w-4 h-4" />
                                    </motion.button>
                                </Link>
                            </div>
                        </motion.div>
                    </div>

                    {/* Right: HUD Preview */}
                    <motion.div
                        initial={{ opacity: 0, x: 40 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 1, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
                        className="relative"
                    >
                        <div className="glass rounded-2xl p-6 shadow-gold-lg border border-gold/10">
                            {/* Mini HUD header */}
                            <div className="flex items-center justify-between mb-5">
                                <div className="flex items-center gap-2">
                                    <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                                    <span className="text-xs text-steel font-mono">LIVE · AeroHire HQ</span>
                                </div>
                                <span className="text-xs text-gold font-mono">17.03.26 · 10:19</span>
                            </div>

                            {/* Match score rings */}
                            <div className="flex justify-center mb-6">
                                <div className="relative w-40 h-40">
                                    <svg className="w-full h-full -rotate-90">
                                        <circle cx="80" cy="80" r="70" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="8" />
                                        <circle
                                            cx="80" cy="80" r="70" fill="none"
                                            stroke="#D4AF37" strokeWidth="8"
                                            strokeDasharray="440" strokeDashoffset="66"
                                            strokeLinecap="round"
                                        />
                                        <circle cx="80" cy="80" r="52" fill="none" stroke="rgba(141,150,168,0.2)" strokeWidth="6" />
                                        <circle
                                            cx="80" cy="80" r="52" fill="none"
                                            stroke="#8D96A8" strokeWidth="6"
                                            strokeDasharray="327" strokeDashoffset="65"
                                            strokeLinecap="round"
                                        />
                                    </svg>
                                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                                        <span className="font-display text-3xl text-gold font-semibold">85%</span>
                                        <span className="text-steel text-xs font-sans mt-1">Match Score</span>
                                    </div>
                                </div>
                            </div>

                            {/* Mini pipeline */}
                            <div className="space-y-2">
                                {[
                                    { title: "Senior Product Designer", co: "Airbus", status: "Offer", color: "status-offer" },
                                    { title: "UX Lead", co: "Emirates", status: "Interviewing", color: "status-interviewing" },
                                    { title: "Head of Design", co: "LVMH", status: "Applied", color: "status-applied" },
                                ].map((item) => (
                                    <div key={item.title} className="flex items-center gap-3 p-3 glass-dark rounded-lg">
                                        <div className="w-8 h-8 glass-navy rounded flex items-center justify-center flex-shrink-0">
                                            <Plane className="w-3.5 h-3.5 text-gold" />
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <p className="text-charcoal dark:text-white text-xs font-medium truncate">{item.title}</p>
                                            <p className="text-steel-dark dark:text-steel text-xs">{item.co}</p>
                                        </div>
                                        <span className={`badge ${item.color}`}>{item.status}</span>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Floating accent card */}
                        <motion.div
                            className="absolute -bottom-6 -left-6 glass-gold rounded-xl p-4 shadow-gold"
                            animate={{ y: [0, -8, 0] }}
                            transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                        >
                            <p className="text-gold text-xs font-mono uppercase tracking-wider mb-1">New Match</p>
                            <p className="text-charcoal dark:text-white text-sm font-display font-medium">Senior Engineer · Google</p>
                            <p className="text-gold text-lg font-mono font-bold">91% ↑</p>
                        </motion.div>
                    </motion.div>
                </div>
            </section>

            {/* Stats */}
            <section className="border-y border-white/5">
                <div className="max-w-7xl mx-auto px-6 py-12 grid grid-cols-2 md:grid-cols-4 gap-8">
                    {stats.map((stat, i) => (
                        <motion.div
                            key={stat.label}
                            className="text-center"
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: i * 0.1, duration: 0.6 }}
                        >
                            <p className="font-display text-4xl font-semibold text-gold-gradient mb-2">{stat.value}</p>
                            <p className="text-steel text-sm font-sans">{stat.label}</p>
                        </motion.div>
                    ))}
                </div>
            </section>

            {/* Features */}
            <section id="features" className="py-28">
                <div className="max-w-7xl mx-auto px-6">
                    <motion.div
                        className="text-center mb-16"
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                    >
                        <div className="inline-flex items-center gap-2 px-3 py-1.5 glass rounded-full mb-6">
                            <span className="text-steel text-xs font-mono uppercase tracking-widest">System Capabilities</span>
                        </div>
                        <h2 className="section-heading text-5xl mb-4">
                            Built for those who{" "}
                            <span className="text-gold-gradient">command the skies.</span>
                        </h2>
                        <p className="text-steel max-w-xl mx-auto font-sans leading-relaxed">
                            Every feature engineered with precision. No noise, no distractions—
                            only the intelligence that moves your career forward.
                        </p>
                    </motion.div>

                    <div className="grid md:grid-cols-3 gap-6">
                        {features.map((feature, i) => {
                            const Icon = feature.icon;
                            return (
                                <motion.div
                                    key={feature.title}
                                    className="card group hover:border-gold/20 hover:shadow-card-hover transition-all duration-500"
                                    initial={{ opacity: 0, y: 30 }}
                                    whileInView={{ opacity: 1, y: 0 }}
                                    viewport={{ once: true }}
                                    transition={{ delay: i * 0.15, duration: 0.7 }}
                                    whileHover={{ y: -4 }}
                                >
                                    <div className="w-12 h-12 glass-gold rounded-xl flex items-center justify-center mb-5 group-hover:shadow-glow transition-all duration-300">
                                        <Icon className="w-6 h-6 text-gold" />
                                    </div>
                                    <h3 className="font-display text-xl font-semibold mb-3">{feature.title}</h3>
                                    <p className="text-steel text-sm leading-relaxed font-sans">{feature.description}</p>
                                </motion.div>
                            );
                        })}
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="py-24 border-t border-white/5">
                <div className="max-w-4xl mx-auto px-6 text-center">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                    >
                        <h2 className="section-heading text-5xl mb-6">
                            Ready for <span className="text-gold-gradient">clearance?</span>
                        </h2>
                        <p className="text-steel font-sans mb-10 text-lg">
                            Join the executives already flying first class in their careers.
                        </p>
                        <Link href="/register">
                            <motion.button
                                className="btn-primary text-base px-10 py-5"
                                whileHover={{ scale: 1.03 }}
                                whileTap={{ scale: 0.97 }}
                            >
                                Request Access
                                <ArrowRight className="w-5 h-5" />
                            </motion.button>
                        </Link>
                    </motion.div>
                </div>
            </section>

            {/* Footer */}
            <footer className="border-t border-white/5 py-8">
                <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
                    <div className="flex items-center gap-2">
                        <div className="w-6 h-6 bg-gold rounded-sm flex items-center justify-center">
                            <Plane className="w-3 h-3 text-charcoal rotate-45" />
                        </div>
                        <span className="font-display text-sm text-steel">AeroHire</span>
                    </div>
                    <p className="text-steel/50 text-xs font-sans">
                        © 2026 AeroHire. All rights reserved.
                    </p>
                </div>
            </footer>
        </main>
    );
}
